# docker-compose.yml
   version: '3.8'
   services:
    mysql:
      image: mysql:8.0
      restart: on-failure
      environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
    php:
       build:
         context: .
         dockerfile: docker/php/Dockerfile
       restart: on-failure
       env_file:
         - .env
       volumes:
         - './apps/rest/:/usr/src/app'
       user: ${LOCAL_USER}

    nginx:
      image: nginx:1.19.0-alpine
      restart: on-failure
      volumes:
        - './apps/rest/public/:/usr/src/app'
        - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
      ports:
        - '${NGINX_PORT}:80'
      depends_on:
        - php
        
        
